name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run update script
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name 'onebirdrocks'
          git config --global user.email 'rymrocks@163.com'
          git add README.md
          git commit -m 'Update README with latest stats'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
