name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.7.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run update script
        run: python update_readme.py

      - name: Debug PAT Permissions
        run: |
          echo "Checking PAT permissions"
          curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/user/repos


      - name: Commit changes
        run: |
          git config --global user.name 'onebirdrocks'
          git config --global user.email 'rymrocks@163.com'
          git add README.md
          git commit -m 'Update README with latest stats'
          git push git@github.com:onebirdrocks/Awesome-GenAI.git
